from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path


def main() -> int:
    # This is a simple example tool script.
    #
    # Lifeguard verification does not execute tools, but people reading the example
    # spec may try to run the tool locally. This script makes that safe and obvious.
    workspace = Path("/workspace") if Path("/workspace").exists() else Path.cwd()
    report_dir = workspace / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)

    report_path = report_dir / "example_report.md"
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "note": "Example report generated by lifeguard/examples/write_report.py",
    }

    report_path.write_text(
        "# Example report\n\n"
        "This is a sample report file created by the Lifeguard examples.\n\n"
        "Metadata:\n\n"
        "```json\n"
        f"{json.dumps(payload, indent=2)}\n"
        "```\n",
        encoding="utf-8",
    )
    print(str(report_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

